### ISSUE TITLE
[design] NavBar 구현

### ISSUE THREAD

**Issue by 2unhi** [KUSITMS-30th-TEAM-A/frontend#2]
## 📄구현할 기능 요약

페이지 하단 네비게이션 바를 구현한다.

## ✅작업 상세 내용

- [ ] 공통 컴포넌트 NavBar 구현

**Comment by inaemon** [comment]
feat 말구 design으로 해야할 거 같슴댱

**Comment by 2unhi** [comment]
🎨 수정하겠습니다!
