### ISSUE TITLE
[design] 메인홈, 추천 질문, 추천 결과, 구역 가이드 디자인과 이벤트 수저엉

### ISSUE THREAD

**Issue by inaemon** [KUSITMS-30th-TEAM-A/frontend#57]
## 📄구현할 기능 요약

> 추가하려는 기능에 대해 간결하게 설명해주세요.
기획자, 디자이너들의 qa sheet를 참고하여 전체 페이지 디자인과 기능을 수정한다.

## ✅작업 상세 내용

- [x] 메인 홈 일반 폰, 프로 폰 반응형 최적화
- [x] 추천 질문 1 페이지 헤더 바 미니폰 반응형 추가
- [x] 추천 결과 페이지에서 자세히 보러가기 버튼 클릭시 전체 좌석을 받아오는 API 호출 및 드롭다운에 좌석 넣기
- [x] 드롭다운 외부를 클릭시에도 드롭다운이 닫히게 이벤트 추가

## 📚참고할만한 자료(선택)
배포 그만하고 싶다,, 반응형 실험 괴롭다

![image](https://github.com/user-attachments/assets/8e95648f-29be-4744-a993-ff5387944775)
![image](https://github.com/user-attachments/assets/34ca8ef4-bddd-4144-b787-a6f8aa4fa21c)

야도 고쳐야하네

![image](https://github.com/user-attachments/assets/cf770468-25f3-4de6-94af-8d363d4baa54)

**Comment by 2unhi** [comment]
수저엉....엉엉😭

**Comment by inaemon** [comment]
> 수저엉....엉엉😭

ㅋㅋㅋㅋㅋㅋ흐겅😿
